name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0

      - uses: pnpm/action-setup@v4.1.0

      - uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install

      - run: pnpm run lint
